#ifndef MICROPROC_MACROS
#define MICROPROC_MACROS

#define INSTRUCTIONS 10
#define INSTRUCTION_SIZE 14
#define ISZ INSTRUCTION_SIZE

#define PRECISION 8

enum INSTRUCTIONS_NAMES{SUM,SUB,MULT,LOAD,STORE,JZ,JNZ,JEQ};

#endif//MICROPROC_MACROS
