#ifndef MICROPROC_MACROS
#define MICROPROC_MACROS

#define INSTRUCTIONS 10
#define INSTRUCTION_SIZE 14
#define ISZ INSTRUCTION_SIZE
#define ARGUMENTSZ 5
#define PRECISION 8
#define OPCODESIZE 4 
enum INSTRUCTIONS_NAMES{SUM,SUB,MULT,DIV,LOAD,STORE,JZ,JNZ,JEQ,JNEQ,AND,OR};

#endif //MICROPROC_MACROS
