#ifndef MICROPROC_MACROS
#define MICROPROC_MACROS

#define INSTRUCTIONS 10
#define ARGUMENTSZ 5
#define ARG_N 3
#define PRECISION 8
#define OPCODESIZE 4
#define INSTRUCTION_SIZE ( ARGUMENTSZ * ARG_N + OPCODESIZE )
#define ISZ INSTRUCTION_SIZE
enum INSTRUCTIONS_NAMES{SUM,SUB,MULT,DIV,LOAD,STORE,JZ,JNZ,JEQ,JNEQ,AND,OR};

#define instrMem_filename "in.bin"
int clkc=0;

#endif //MICROPROC_MACROS
